# Generated by Django 3.0.4 on 2020-05-16 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BlogIcon', models.ImageField(default='team.png', upload_to='Blogger_profile/')),
                ('BloggerName', models.CharField(max_length=50, unique=True)),
                ('About', models.CharField(max_length=500)),
                ('Founder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Founders', to=settings.AUTH_USER_MODEL)),
                ('Members', models.ManyToManyField(related_name='Members', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
