# Generated by Django 3.0.4 on 2020-05-18 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bloggers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogger',
            old_name='BlogIcon',
            new_name='image',
        ),
    ]
