# Generated by Django 3.0.4 on 2020-05-18 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bloggers', '0002_auto_20200518_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogger',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
    ]
