# Generated by Django 3.0.4 on 2020-05-19 05:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Bloggers', '0003_blogger_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogger',
            name='Members',
            field=models.ManyToManyField(related_name='bloggerMembers', to=settings.AUTH_USER_MODEL),
        ),
    ]
