# Generated by Django 3.0.4 on 2020-05-31 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_auto_20200516_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connetions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Phone', models.IntegerField(blank=True, help_text='enter Number with country code(+91 for india)', max_length=15, null=True)),
                ('instagram', models.URLField(blank=True, max_length=999, null=True)),
                ('FaceBook', models.URLField(blank=True, max_length=999, null=True)),
                ('Linkdin', models.URLField(blank=True, max_length=999, null=True)),
                ('YouTube', models.URLField(blank=True, max_length=999, null=True)),
                ('Twitter', models.URLField(blank=True, max_length=999, null=True)),
                ('TikTok', models.URLField(blank=True, max_length=999, null=True)),
                ('Website', models.URLField(blank=True, max_length=999, null=True)),
                ('Blogs', models.URLField(blank=True, max_length=999, null=True)),
                ('YourQuotes', models.URLField(blank=True, max_length=999, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
