# Generated by Django 3.0.4 on 2020-05-19 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Bloggers', '0004_auto_20200519_1126'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Blogtiltle', models.CharField(max_length=50)),
                ('Blog', models.FileField(upload_to='Blogs/')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('BloggerAc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bloggerAc', to='Bloggers.Blogger')),
                ('Members', models.ManyToManyField(related_name='BlogMembers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
