# Generated by Django 3.0.4 on 2020-05-19 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPost', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='Blog',
        ),
        migrations.AddField(
            model_name='blog',
            name='UpBlog',
            field=models.FileField(null=True, upload_to='upBlogs/'),
        ),
    ]
