# Generated by Django 3.0.4 on 2020-05-19 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPost', '0002_auto_20200519_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='UpBlog',
            field=models.FileField(blank=True, null=True, upload_to='upBlogs/'),
        ),
    ]
