# Generated by Django 3.0.4 on 2020-05-19 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPost', '0003_auto_20200519_1211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='Members',
            new_name='Authors',
        ),
    ]
