# Generated by Django 3.0.4 on 2020-05-19 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BlogPost', '0004_auto_20200519_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Uploader',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='bloguploader', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
