# Generated by Django 3.0.4 on 2020-05-22 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPost', '0007_auto_20200522_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='UpBlog',
            field=models.URLField(blank=True, max_length=999, null=True),
        ),
    ]
