# Generated by Django 3.0.4 on 2020-05-24 07:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BlogPost', '0011_auto_20200522_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Discription',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='Dislikes',
            field=models.ManyToManyField(blank=True, related_name='blogpostdislike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blog',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='blogpostLikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
