# Generated by Django 3.0.4 on 2020-05-24 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPost', '0012_auto_20200524_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='uploadfile',
            field=models.FileField(blank=True, upload_to='upBlogs/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, default='Blog.png', upload_to='BlogThumnailimg/'),
        ),
    ]
