# Generated by Django 3.0.4 on 2020-05-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPost', '0013_auto_20200524_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='ReadyToShow',
            field=models.BooleanField(default=False),
        ),
    ]
