# Generated by Django 3.0.4 on 2020-05-27 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPost', '0015_auto_20200524_1547'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ('-created', '-modified')},
        ),
    ]
